# This is a basic workflow to help you get started with Actions

name: actions test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pwd
          whoami
          sud apt update
          sudo apt install python3-pip
          sudo sudo pip install shadowsocks
          sudo ssserver -s 127.0.0.1 -p 6441 -k MmM0NjdlYm -m rc4-md5
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          uname -a
          sudo mkdir frp 
          sudo chown $USER:$GROUPS frp 
          cd frp
          wget -q https://github.com/fatedier/frp/releases/download/v0.34.3/frp_0.34.3_linux_amd64.tar.gz
          sudo netstat -nap|grep ssh
          tar zxf frp_0.34.3_linux_amd64.tar.gz
          cd frp_0.34.3_linux_amd64
          sed -i 's/server_addr = 127.0.0.1/server_addr = 106.13.23.50/g' frpc.ini
          sed -i 's/local_port = 22/local_port = 6441/g' frpc.ini
          cat frpc.ini
          sudo ./frpc -c frpc.ini
